#+OPTIONS: html-postamble:nil
#+OPTIONS: toc:nil
#+OPTIONS: title:nil
#+OPTIONS: num:nil
#+OPTIONS: ::800
#+OPTIONS: html-style:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+STARTUP:    showall
#+TITLE:      Waste Management
#+AUTHOR:     Adam Massmann
#+EMAIL:      akm2203 "at" columbia "dot" edu
#+LANGUAGE:   en

** Solid and Hazardous Waste Management

Welcome! This is the course website for Solid and Hazardous Waste
Management (EEAE 4160). This Learning Community's goal is to
collectively design solid/hazardous waste-related interventions that
improve the health of the Earth system.

- [[https://docs.google.com/document/d/1c4BuOWJOin1FxwsyJ0vJAVV42QEq9WeRSfVbQaDdsxA/edit?usp=sharing][Community agreement]]

- Instructor/facilitator: Adam Massmann (uni: akm2203; office: Mudd
  905D)
  - Office Hours: Wednesdays 4-5; Thursdays 11-12
- TA/facilitator: Elizabeth Czekaj (uni: eac2280; [[https://docs.google.com/spreadsheets/d/1IXQtuIn5-8ZDRwMEd3FOCOB_d-qPSripqrjRP-Iyq9k/edit?usp=sharing][office hours sign up]])

*** Current Tasks

- Nothing specific to do; but please review your groups' spreadsheet,
  think about potential project areas and ideas, and if you are
  feeling stuck consider brainstorming some steps or research that
  might help generate ideas.

- [[file:past-tasks.org][Past tasks]]

*** Schedule

**** Week 1
***** Tuesday, September 3

Introduction to the course and the Learning Community approach. [[file:notes/class-01.pdf][Slides]].

***** Thursday, September 5

Introduce solid and hazardous waste management through a discussion of
ideas for group projects. [[https://docs.google.com/presentation/d/1HCBCT0pIRRQfNjMzHfBwiMJ6fF_HGmuX8ezVGRhnELw/][Elizabeth's slides]]. [[file:notes/class-02.pdf][Adam's slides]]. [[https://docs.google.com/document/d/1OfAhHrfSOXpWMPKGUAHosZwHqPhA13rbvO2wXWrCwXY/edit?usp=sharing][Adam's
example Doc]], [[https://docs.google.com/document/d/1Ox4bEAXZciASeBRgg5Q0FrnwA9am6ZeZUuEs8__MrHM/edit?usp=drive_link][Collab Doc #1]]; [[https://docs.google.com/document/d/15Qi66vQO25PKPGAJrLbdSi32qo2Xh-8vlqJoIRQzqgE/edit?usp=drive_link][Collab Doc #2]]; [[https://docs.google.com/document/d/1JP1uaAYvL3oDQCkT37MIV7l1rOXQUc4oanmIR1SIhO0/edit?usp=drive_link][Collab Doc
#4]]; [[https://docs.google.com/document/d/1zf_NNNLZHIRnAgkC2P3tah2BuPwIrINhX_ZLxtOuam8/edit?usp=drive_link][Collab Doc #5]]; [[https://docs.google.com/document/d/1ohw4qIIg7JEPXp5vu2i7kDmoGfYeQ8NItBEOaR16GJc/edit?usp=drive_link][Collab Doc #6]].

**** Week 2

***** Tuesday, September 10

Meet in groups to decide on group project ideas. [[file:notes/class-03.pdf][Slides]]. [[https://docs.google.com/document/d/1ALFitImhK-TqYWsySX7dYzzpQC3g8D6gY5iYPwqKRlE/edit?usp=drive_link][Collective
project ideas]]. [[https://docs.google.com/document/d/1gTMMrQiX4P3nvNSUEEEKMjAw_vIQ9UaeiwbINIgZy2g/edit?usp=drive_link][Group 1 brainstorm]]; [[https://docs.google.com/document/d/1q4bxPi2cUtp5ODYC_pR6s1ClsHs9OS5nUYdUg5uHoIQ/edit?usp=drive_link][Group 2 brainstorm]]; [[https://docs.google.com/document/d/1fV3xm5Hg_yNpYr5kDAeIQnIFszflGldsLq1eOKrnKbo/edit?usp=drive_link][Group 3
brainstorm]]; [[https://docs.google.com/document/d/1Lx_dloi_9BKl8oeGD9gA_v8zLfgWTZkLXTRbfxwscCQ/edit?usp=drive_link][Group 4 brainstorm]]; [[https://docs.google.com/document/d/1YgN0VIEdGiGSvrxy_tarrO9R3ihTsLbYNYOpK9ox87o/edit?usp=drive_link][Group 5 brainstorm]]; [[https://docs.google.com/document/d/1pw06CGXdSquNDzx16NDK0YaIuJqSuZer7hfk6-Z5m2o/edit?usp=drive_link][Group 6
brainstorm.]]

***** Thursday, September 12

Discussion of active learning, lectures, and background knowledge;
meet in groups for background research and/or to converge toward a
project idea. [[file:notes/class-04.pdf][Notes]]. [[https://docs.google.com/document/d/1txOo-t1B5rozuaQ-YxjeBqetycyRpXdQwI4MyIsdeYc/edit?usp=drive_link][Class structure brainstorm]], [[https://docs.google.com/document/d/1ALFitImhK-TqYWsySX7dYzzpQC3g8D6gY5iYPwqKRlE/edit?usp=drive_link][Collective project ideas]], [[https://docs.google.com/document/d/1gTMMrQiX4P3nvNSUEEEKMjAw_vIQ9UaeiwbINIgZy2g/edit?usp=drive_link][Group 1 brainstorm]]; [[https://docs.google.com/document/d/1q4bxPi2cUtp5ODYC_pR6s1ClsHs9OS5nUYdUg5uHoIQ/edit?usp=drive_link][Group 2
brainstorm]]; [[https://docs.google.com/document/d/1fV3xm5Hg_yNpYr5kDAeIQnIFszflGldsLq1eOKrnKbo/edit?usp=drive_link][Group 3 brainstorm]]; [[https://docs.google.com/document/d/1Lx_dloi_9BKl8oeGD9gA_v8zLfgWTZkLXTRbfxwscCQ/edit?usp=drive_link][Group 4 brainstorm]]; [[https://docs.google.com/document/d/1YgN0VIEdGiGSvrxy_tarrO9R3ihTsLbYNYOpK9ox87o/edit?usp=drive_link][Group 5
brainstorm]]; [[https://docs.google.com/document/d/1pw06CGXdSquNDzx16NDK0YaIuJqSuZer7hfk6-Z5m2o/edit?usp=drive_link][Group 6 brainstorm.]]

**** Week 3

***** Tuesday September 17th

Present group project ideas and introduce group members?

**** Week 14

***** Thursday, December 5th

Collective reflection, feedback, and grade; see [[https://docs.google.com/document/d/1uYVIAEvPjDBc2uf91WIBS9z12h7s3YL8ezDSh-ITIf4/edit?usp=sharing][learning objectives]].

*** Background Material and Broad Perspectives

- [[https://drive.google.com/drive/folders/1rUqV6C6ePlatwTJeKprhtVdOv_epms-O?usp=drive_link][Past Version of This Course's Notes]]
- [[https://ctl.columbia.edu/resources-and-technology/resources/project-based-learning/][MIT OpenCourseWare DLab: Waste]] (undergrad level)
  - [[file:papers/MITEC_716F15_Biohaz2.pdf][example class project from the course]]
- [[https://ocw.mit.edu/courses/1-34-waste-containment-and-remediation-technology-spring-2004/pages/readings/][MIT OpenCourseWare Waste Containment and Remediation Technology]]  (grad level)

*** Links
- [[https://drive.google.com/drive/folders/1SNvL7LhQjOsWKYlftEOHrcFp9EsyewzV?usp=drive_link][Google Drive Folder]]
- [[file:adam-notes.org][Adam's random notes]]

*** Learning-related links

- [[https://drive.google.com/file/d/15krpTtVov1yJicgP_5S_DpE81Le_xOde/view?usp=drive_link]["Teaching to Transgress: Education as the Practice of Freedom" by bell hooks]]

- [[https://drive.google.com/file/d/1u0GxYz1dk8R5aVmFjtTsSlaP-PJ09Y0r/view?usp=drive_link]["Who's Asking?: Native Science, Western Science, and Science Education" by Bang and Medin]]

- [[https://drive.google.com/file/d/1aR_8sMzea4yCcF-v8OgYCoAfXvtrFzd_/view?usp=drive_link]["The Spark of Learning" by Sarah Rose Cavanagh.]]

- [[file:papers/freeman-et-al-2014-active-learning-increases-student-performance-in-science-engineering-and-mathematics.pdf]["Active learning increases student performance in science, engineering, and mathematics" by Freeman et al. (2014).]]

- [[file:papers/active-learning_hands-on-meets-minds-on.pdf]["Active learning: 'Hands on' meets 'minds-on'"]]. (collection of small
  articles by various authors)

- [[https://ctl.columbia.edu/resources-and-technology/resources/project-based-learning/][Columbia CTL's Project Based Learning Resource Page]]
