#+OPTIONS: html-postamble:nil
#+OPTIONS: toc:nil
#+OPTIONS: title:nil
#+OPTIONS: num:nil
#+OPTIONS: ::800
#+OPTIONS: html-style:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+STARTUP:    showall
#+TITLE:      Waste Management
#+AUTHOR:     Adam Massmann
#+EMAIL:      akm2203 "at" columbia "dot" edu
#+LANGUAGE:   en

** Solid and Hazardous Waste Management

Welcome! This is the course website for Solid and Hazardous Waste
Management (EEAE 4160). This Learning Community's goal is to
collectively design solid/hazardous waste-related interventions that
improve the health of the Earth system.

- [[https://docs.google.com/document/d/1c4BuOWJOin1FxwsyJ0vJAVV42QEq9WeRSfVbQaDdsxA/edit?usp=sharing][Community agreement]]

- Instructor/facilitator: Adam Massmann (uni: akm2203; office: Mudd
  905D)
  - Office Hours: Wednesdays 4-5; Thursdays 11-12
- TA/facilitator: Elizabeth Czekaj (uni: eac2280; [[https://docs.google.com/spreadsheets/d/1IXQtuIn5-8ZDRwMEd3FOCOB_d-qPSripqrjRP-Iyq9k/edit?usp=sharing][office hours sign up]])

*** Current Tasks


**** Before Thursday's Class (September 5)
- Think about solid and hazardous waste management and develop some
  ideas on the problems you may want to work on for the group
  project. (we will discuss these ideas in class on Thursday)
- Record a name pronunciation in Courseworks if you have not already.
- (optional) Add any edits or comments to the [[https://docs.google.com/document/d/1c4BuOWJOin1FxwsyJ0vJAVV42QEq9WeRSfVbQaDdsxA/edit?usp=sharing][community agreement]].
- (optional) Fill out the [[https://www.when2meet.com/?26223463-ilVgY][when2meet]] with your availability to attend
  office hours.

**** By Thursday night (September 5)

- Fill out the [[https://docs.google.com/forms/d/e/1FAIpQLSd2_NgWkrfuU_SVYc58uAqB0t4l8RCIS_FtKWTn7IQ5lipcJQ/viewform?usp=sf_link][course/project survey]].

*** Schedule

**** Week 1
***** Tuesday, September 3

Introduction to the course and the Learning Community approach. [[file:notes/class-01.pdf][Slides]].

***** Thursday, September 5

Introduce solid and hazardous waste management through a discussion of
ideas for group projects. [[https://docs.google.com/presentation/d/1HCBCT0pIRRQfNjMzHfBwiMJ6fF_HGmuX8ezVGRhnELw/][Elizabeth's slides]]. [[file:notes/class-02.pdf][Adam's slides]]. [[https://docs.google.com/document/d/1OfAhHrfSOXpWMPKGUAHosZwHqPhA13rbvO2wXWrCwXY/edit?usp=sharing][Adam's
example Doc]], [[https://docs.google.com/document/d/1Ox4bEAXZciASeBRgg5Q0FrnwA9am6ZeZUuEs8__MrHM/edit?usp=drive_link][Collab Doc #1]]; [[https://docs.google.com/document/d/15Qi66vQO25PKPGAJrLbdSi32qo2Xh-8vlqJoIRQzqgE/edit?usp=drive_link][Collab Doc #2]]; [[https://docs.google.com/document/d/1JP1uaAYvL3oDQCkT37MIV7l1rOXQUc4oanmIR1SIhO0/edit?usp=drive_link][Collab Doc
#4]]; [[https://docs.google.com/document/d/1zf_NNNLZHIRnAgkC2P3tah2BuPwIrINhX_ZLxtOuam8/edit?usp=drive_link][Collab Doc #5]]; [[https://docs.google.com/document/d/1ohw4qIIg7JEPXp5vu2i7kDmoGfYeQ8NItBEOaR16GJc/edit?usp=drive_link][Collab Doc #6]].

**** Week 2

***** Tuesday, September 10

Meet in groups to decide on group project ideas.

***** Thursday, September 12

Present group project ideas and introduce group members.

**** Week 14

***** Thursday, December 5th

Collective reflection, feedback, and grade; see [[https://docs.google.com/document/d/1uYVIAEvPjDBc2uf91WIBS9z12h7s3YL8ezDSh-ITIf4/edit?usp=sharing][learning objectives]].

*** Links
- [[https://drive.google.com/drive/folders/1SNvL7LhQjOsWKYlftEOHrcFp9EsyewzV?usp=drive_link][Google Drive Folder]]
- [[file:adam-notes.org][Adam's random notes]]
