* Solid and Hazardous Waste Management (#7) [Please sit with your project group]

** Case Studies! (until ~2:05)

- Please sit with your project group.

- If you haven't already, I recommend filling in your individual goals
  and available resources from last week's Group Introduction
  doc. Also agree on a group name/mascot.

- The case study doc is now in your GDrive folder. Take some time in
  your case study search: look for something that is implemented
  currently/historically and has a *narrow scope*.

- These activities are tools for you to use as you see fit.

- While you are working: be aware that groups are an opportunity for differentiation.

  - If you want more or less structure let me know.

  - While I won't force anybody to do things, collective
    accountability and deadlines can help structure progress. If you
    are able to agree on some accountability structure and/or
    deadlines, let me know so I can support you in achieving your
    deadlines and group accountability.

** Try and end every group work session with a list of "next steps" and/or "open questions"

- Take a moment as a group and brainstorm and write down some next
  steps and/or open questions.

- If you're particularly interested in one of the next steps or
  open questions, put your name down next to it and share what you find in
  Thursday's share out and/or next Tuesday's group work.

** Reflect

- Take a couple of minutes to independently reflect on your group work
  and dynamics thus far after 2 work sessions; for example:

  - What is working well in your group work?

  - It's early days, but is there room for improvement in the group work
    and dynamics? How can that improvement be realized?

  - Ideas on structures that would help guide your projects?

  - Any structures (e.g., case study doc) that feel restrictive or
    limiting to your project?
