* Solid and Hazardous Waste Management (#4) [Please sit with your project group]

** Mindfulness

** Website Updates

** Last class and lectures

- Can't say enough how happy and excited I am that you all were
  providing feedback and actively participating in shaping your
  learning experience. That was a big goal I had for this class.

- I thought long and hard about lecturing on Solid and Hazardous Waste
  Management, but still can not get onboard, because I feel it would
  get away from evidence-based active learning, and also run the risk
  of biasing the learning with my own filters and views.

- This reflection also made me realize I might not be scaffolding and
  justifying active, project based learning enough.

** Active learning
- Active learning is "a suite of pedagogical approaches that engage
  students in the construction of knowledge through activities and
  discussion in class, as opposed to passively listening to an
  expert." - Theobald and Freeman in "[[file:../papers/active-learning_hands-on-meets-minds-on.pdf][Active Learning: Hands on Meets
  Minds On]]"

** Active learning improves learning outcomes
- "The results raise questions about the continued use of traditional
  lecturing as a control in research studies, and support active
  learning as the preferred, empirically validated teaching practice
  in regular classrooms." - Freeman et al. in "[[file:../papers/freeman-et-al-2014-active-learning-increases-student-performance-in-science-engineering-and-mathematics.pdf][Active Learning
  Increases Student Performance in Science, Engineering, and Mathematics]]."

** While students learn more with active learning, they perceive they learn more in lectures!
- "Students learned significantly more with active learning (as
  expected), and they also felt that they learned from it—but their
  feeling of learning was more pronounced with the well-presented
  traditional lectures." - Deslauriers et al in  "[[file:../papers/active-learning_hands-on-meets-minds-on.pdf][Active Learning: Hands on Meets
  Minds On]]"

** Counterintuitively, it might be a good thing if folks are (now or in the future) feeling daunted, confused, frustrated, or doubtful
- It's okay and normal to feel confused, frustrated, etc. ([[https://drive.google.com/file/d/1aR_8sMzea4yCcF-v8OgYCoAfXvtrFzd_/view?usp=sharing][Cavanagh]])
- It's normal to resist new forms of teaching/learning ([[https://drive.google.com/file/d/15krpTtVov1yJicgP_5S_DpE81Le_xOde/view?usp=drive_link][hooks]])
- These feelings can be a part of a rewarding learning process
  ([[https://drive.google.com/file/d/15krpTtVov1yJicgP_5S_DpE81Le_xOde/view?usp=drive_link][hooks]], [[https://drive.google.com/file/d/1aR_8sMzea4yCcF-v8OgYCoAfXvtrFzd_/view?usp=sharing][Cavanagh]])
- *Important*: discomfort or mild anxiety can help or be a part of the
  learning process, but high anxiety is detrimental; so please please
  communicate if you are feeling really anxious about anything in this
  class.
- Mindfulness can help ([[https://drive.google.com/file/d/1aR_8sMzea4yCcF-v8OgYCoAfXvtrFzd_/view?usp=sharing][Cavanagh]], Nhat Hanh)

** I'm asking for your trust
- That this more active, project based learning can work

- That I hear your feedback and value it. Please please keep giving me
  feedback and contributing learning ideas; the fact that I won't
  lecture on Solid and Hazardous Waste Management does not mean I
  didn't hear and really think hard about your feedback (I feel like
  Tuesday could be a breakthrough). Within active learning, there are
  so many knobs to tune (for example structure), and these can be
  tailored to each group and individual .

- Let's try this! There's tons of opportunity and what is the worst
  that can happen?

** ...and I also want to advertise what we've accomplished in two days of class with tons of logistical challenges

- This [[https://docs.google.com/document/d/1ALFitImhK-TqYWsySX7dYzzpQC3g8D6gY5iYPwqKRlE/edit][long list of project ideas]] that exceeds the breadth of any of
  the course syllabus I've seen (past 4160, MIT courses)

- These learning objectives:
  1. Define solid waste.
  2. Define hazardous waste.
  3. Identify and define solid and/or hazardous waste streams in
     different project areas.
  4. Generate exploratory intervention ideas related to different
     project areas.

- Discussion on perspective taking (earthworms, bacteria)
  and reciprocity in waste management.

- Discussion on interdependence and coupling between consumption,
  waste management systems, and behavior.

** Return to Class Structure Brainstorm

** Group meet!
- Introduce yourselves if you have not (names and preferred pronouns)
  - Also introduce something non academic you've enjoyed or been into lately
    (song, book, TV show, food spot, local park, movie, stretch of
    street or trail, museum, sport, etc.)

- Brainstorm a group project idea; brainstorming doc is available from
  the website and in your Group's Google folder.

- Brainstorm a group name or mascot?

- If you would like to do more background research before picking a
  group topic that is fine; I recommend pair research (e.g. 2-3 people
  per a computer/device). Possible tools include the MIT courses
  linked on the website, Thanos's slides, Wikipedia, Google Scholar,
  CLIO, Web of Science.

** How did the group meeting go?


** Next activities: choose our own adventure
- Research approach ([[https://scholar.google.com/][google scholar]], [[https://clio.columbia.edu/][CLIO]], [[https://www-webofscience-com.ezproxy.cul.columbia.edu/wos/woscc/basic-search][web of science]], [[https://www.nypl.org/][nypl]])

- Introduce my project idea
  - Building scale NYC compost, possibly implemented city-wide.

- Return to Groups for more project discussion

- Return to Groups for image hunt

** What would be helpful for next class?

- Anything specific you want me to prepare for Tuesday?

- More or less, or about right, structure to group work?

** Last logistical things

- Edit of community agreement to be more explicit

- Names recordings on Courseworks?

** Thank you! and plan for Tuesday

- Each group will introduce themselves and their initial project ideas
  (or questions and issues they ran into while trying to converge on a
  project idea).
  - Goal: informal, conversational and low stress
