* Solid and Hazardous Waste Management (#5) [Please sit with your project group]
** Mindfulness

** Please don't mistake informality, the fact that I might be teaching differently than what you're used to, or that I will not force you to do things, for a lack of seriousness

- Everything we have done in this class and are doing in this class is
  designed to serve the course learning objective (and I am extremely
  serious about the learning objective).

- I put considerable thought, based on my experience as a consulting
  engineer, academic researcher, and educational developer, into my
  course contributions and design.

- Please be open minded.

** Review of Community Agreement

** Into groups: converge on a topic

- Goal for today:

  1. Group agreement on an initial topic within Solid and Hazardous Waste
     Management.
  2. Community building/getting to know each other, including personal
     goals and availability.

- Collaborative docs serve as a future reference for you, and also
  help me know what's going on so I can better support your project
  management.

- Side note: the culminating deliverable will be project specific, and
  will start to coalesce in a future activity on project goals and
  objectives (but more generally, trust the process).

** Thank you!

- Plan for Thursday is for each group to introduce themselves, their
  topic, and/or any issues or problems they are having.

- These share-out help us learn from each other (breadth), and also
  let us help each other with any issues (practice group problem
  solving, community building, peer feedback).

- Please use office hours! My office is large and there are quite a
  few chairs; definitely enough for a full group and maybe more.

- Is anybody not comfortable with sharing your group's folder with
  everybody else?

- Problem solving opportunity: How do we convince each other to show up?
  Collective accountability?
